apiVersion: v1                              # API-Version für grundlegende Kubernetes-Objekte wie PVCs (PersistentVolumeClaims)
kind: PersistentVolumeClaim                 # Ressourcentyp: PersistentVolumeClaim – fordert persistenten Speicher an
metadata:
  name: petclinic-app-mysql                 # Name des PVCs – wird z. B. im Deployment referenziert (volume.claimName)
spec:                                       # Spezifikation des Speicheranspruchs
  accessModes:                              # Gibt an, wie das Volume vom Pod verwendet werden darf
    - ReadWriteOnce                         # Bedeutet: Nur ein Pod kann gleichzeitig schreiben (häufigster Modus für Block-Storage)
  resources:                                # Ressourcenanforderungen für das Volume
    requests:                               # Speicherbedarf, den der PVC mindestens benötigt
      storage: 1Gi                          # Fordert 1 Gibibyte persistenten Speicher (1Gi = 1024Mi)
  storageClassName: rbd-storagepool-cluster # Gibt die StorageClass an, die verwendet werden soll – hier: Ceph RBD Storage Pool
  volumeMode: Filesystem                    # Der Modus, in dem das Volume bereitgestellt wird – "Filesystem" = als gemountetes Dateisystem (Standard)
---
apiVersion: v1                              # API-Version für grundlegende Kubernetes-Objekte wie PVCs (PersistentVolumeClaims)
kind: PersistentVolumeClaim                 # Ressourcentyp: PersistentVolumeClaim – fordert persistenten Speicher an
metadata:
  name: petclinic-app-mysql                 # Name des PVCs – wird z. B. im Deployment referenziert (volume.claimName)
  labels:
    app: petclinic-app
    app.kubernetes.io/part-of: petclinic-app
spec:                                       # Spezifikation des Speicheranspruchs
  accessModes:                              # Gibt an, wie das Volume vom Pod verwendet werden darf
    - ReadWriteOnce                         # Bedeutet: Nur ein Pod kann gleichzeitig schreiben (häufigster Modus für Block-Storage)
  resources:                                # Ressourcenanforderungen für das Volume
    requests:                               # Speicherbedarf, den der PVC mindestens benötigt
      storage: 1Gi                          # Fordert 1 Gibibyte persistenten Speicher (1Gi = 1024Mi)
  storageClassName: rbd-storagepool-cluster # Gibt die StorageClass an, die verwendet werden soll – hier: Ceph RBD Storage Pool
  volumeMode: Filesystem                    # Der Modus, in dem das Volume bereitgestellt wird – "Filesystem" = als gemountetes Dateisystem (Standard)