apiVersion: v1                                 # API-Version für grundlegende Kubernetes-Ressourcen – Secrets gehören zur core/v1 API
kind: Secret                                   # Ressourcentyp: Secret – enthält sensible Daten wie Passwörter, Tokens oder Keys
metadata:
  name: petclinic-app-mysql                   # Name des Secrets – dieser wird in Deployments oder Pods referenziert
type: Opaque                                   # Typ des Secrets – "Opaque" bedeutet benutzerdefinierte (nicht standardisierte) Schlüssel/Werte
stringData:                                    # stringData erlaubt das direkte Schreiben von Werten als Klartext (werden automatisch in base64 konvertiert)
  DATABASE_HOST: petclinic-app-mysql           # Hostname der MySQL-Datenbank (z. B. für phpMyAdmin)
  MYSQL_DATABASE: petclinic                    # Name der zu erstellenden MySQL-Datenbank
  MYSQL_USER: petclinic                        # Benutzername für den MySQL-Zugriff (z. B. von der Spring Boot App verwendet)
  MYSQL_PASSWORD: petclinic                    # Passwort für den obigen Benutzer (sollte in echtem Einsatz **nicht** so einfach sein!)
  MYSQL_ROOT_PASSWORD: petclinic               # Root-Passwort für den MySQL-Server (wird beim Containerstart benötigt)
