apiVersion: v1
kind: Secret
metadata:
  name: petclinic-app-mysql
type: Opaque
stringData:
  DATABASE_HOST: petclinic-app-mysql
  MYSQL_DATABASE: petclinic
  MYSQL_USER: petclinic
  MYSQL_PASSWORD: petclinic
  MYSQL_ROOT_PASSWORD: petclinic